apiVersion: skaffold/v2beta8
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: stevenhunter/auth
    context: auth
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: stevenhunter/client
    context: client
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: stevenhunter/tickets
    context: tickets
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile    
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*